# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sensor_type', models.CharField(choices=[('DHT22', 'DHT22')], max_length=100)),
                ('value_type', models.CharField(choices=[('temperature', 'temperature [DHT22]'), ('humidity', 'humidity [DHT22]')], max_length=100)),
                ('description', models.TextField()),
                ('position', models.CharField(choices=[('inside', 'temperature [DHT22]'), ('outside', 'humidity [DHT22]')], max_length=100)),
                ('unit', models.CharField(choices=[('°C', '°C'), ('Pa', 'Pa')], max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterField(
            model_name='cycle',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='box.Box'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='box.Cycle'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='box.Cycle'),
        ),
    ]
