# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20160423_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='hourly_step',
            field=models.IntegerField(default=5, help_text='change per hour in percent'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='uv_start_level',
            field=models.IntegerField(default=50, help_text='start uv level in percent'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='water_start_level',
            field=models.IntegerField(default=50, help_text='start water level in percent'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='position',
            field=models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('°C', '°C'), ('%', '%'), ('Pa', 'Pa')], max_length=100),
        ),
    ]
