# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('DHT22', 'DHT22'), ('photoresistor', 'photoresistor'), ('FC28', 'FC28')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('°C', '°C'), ('%', '%'), ('Pa', 'Pa'), ('-', '-')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value_type',
            field=models.CharField(choices=[('temperature', 'temperature [DHT22]'), ('humidity', 'humidity [DHT22]'), ('water mark', 'water mark'), ('brightness', 'brightness')], max_length=100),
        ),
    ]
