# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_auto_20160424_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='value_type',
            field=models.CharField(choices=[('temperature', 'temperature [DHT22]'), ('humidity', 'humidity [DHT22]'), ('watermark', 'water mark'), ('brightness', 'brightness')], max_length=100),
        ),
    ]
