# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0009_auto_20160424_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cycle',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='plant',
            field=models.CharField(max_length=255),
        ),
    ]
