# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


def forwards(apps, schema_editor):
    Plant = apps.get_model('box', 'Plant')
    Plant.objects.get_or_create(name_en='cress', name_la='Lepidium sativum')


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0012_auto_20160918_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_en', models.CharField(max_length=255)),
                ('name_la', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('cycle',)},
        ),
        migrations.RunPython(forwards),
    ]
