# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0013_auto_20160924_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='plant_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Plant'),
            preserve_default=False,
        ),
    ]
