# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0014_cycle_plant_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='plant',
        ),
        migrations.RenameField('cycle', 'plant_new', 'plant'),
    ]
