# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0015_auto_20160924_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='wikipedia_en',
            field=models.URLField(blank=True, null=True),
        ),
    ]
