# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0016_plant_wikipedia_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='box.Cycle'),
        ),
    ]
