# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0017_auto_20160926_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='uv_start_level',
            field=models.IntegerField(default=0, help_text='start uv level in percent'),
        ),
    ]
