# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0018_auto_20161016_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='soil',
            field=models.CharField(default='cotton wool (medical)', max_length=255),
            preserve_default=False,
        ),
    ]
