# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0019_cycle_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='soil',
            field=models.CharField(blank=True, choices=[('cotton wool (medical)', 'cotton wool (medical)'), ('cotton wool (cosmetics)', 'cotton wool (cosmetics)'), ('red clay (Seramis)', 'red clay (Seramis)'), ('orchid soil (Orchideenerde)', 'orchid soil (Orchideenerde)')], max_length=255, null=True),
        ),
    ]
