# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0020_auto_20161213_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='adc_used',
            field=models.CharField(blank=True, choices=[('adc10', 'arduino'), ('adc16', 'ADS1x15')], max_length=255, null=True),
        ),
    ]
