# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0021_cycle_adc_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='adc_used',
            field=models.CharField(blank=True, choices=[('adc10', 'Arduino'), ('adc16', 'ADS1x15')], default='adc10', max_length=255),
        ),
    ]
