# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:11
from __future__ import unicode_literals

import box.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0024_auto_20170110_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=box.models.image_directory),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=''),
        ),
    ]
