# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0025_auto_20170110_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='purged',
        ),
    ]
