# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:02
from __future__ import unicode_literals

import box.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0026_auto_20170115_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('plot', models.ImageField(blank=True, max_length=254, null=True, upload_to=box.models.plot_image_directory)),
                ('description', models.CharField(max_length=255)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='box.Cycle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
