# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0027_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='owner',
        ),
    ]
