# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0028_remove_plot_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set([('cycle', 'description')]),
        ),
    ]
