# Generated by Django 2.0 on 2017-12-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0030_auto_20170813_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ('description',), 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('name_en',)},
        ),
        migrations.AlterField(
            model_name='action',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action', to='box.Cycle'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle', to='box.Box'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Plant'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='box.Cycle'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plot',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plot', to='box.Cycle'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='box.Cycle'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor', to='box.Cycle'),
        ),
    ]
