# Generated by Django 2.0.9 on 2018-12-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0032_auto_20171210_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
