# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_delete_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
