# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('axite_id', models.UUIDField()),
                ('full_generation_roundtrip', models.BigIntegerField()),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('axtext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ax.AxText')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
